- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'python3-psycopg2', 'tar', 'virtualenv']
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
    - galaxyproject.tusd
    - galaxyproject.cvmfs
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
    - name: Copy tool config file for galaxy
      copy:
        src: templates/galaxy/config/local_tool_conf.xml.j2
        dest: "{{ galaxy_root }}/config/local_tool_conf.xml"
